In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'This is the first document. This document is the second document. And this is the third one. Is this the first document?'
]
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
#vectorizer.get_feature_names_out()


print(X.shape)


(1, 9)


In [40]:
vectorizer.get_feature_names()

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

In [84]:
import numpy as np
np.array(X.todense())[0][np.argsort(np.array(X.todense()))[0][-3:]]

array([0.47140452, 0.47140452, 0.47140452])

In [87]:
X.todense(), np.argsort(np.array(X.todense()))[0][-3:]

(matrix([[0.11785113, 0.47140452, 0.23570226, 0.47140452, 0.11785113,
          0.11785113, 0.47140452, 0.11785113, 0.47140452]]),
 array([3, 6, 8]))